### ISSUE TITLE
About image transforms

### ISSUE THREAD

**Issue by nijianmo** [jfhealthcare/Chexpert#11]
Hi, thanks for open-sourcing this nice work!!

I found in the config example.json, the use_transforms_type is set to 'Aug'. I wonder what kind of augmentation did you use? Based on the imgaug.py, it looks like you only apply RandomAffine (https://github.com/jfhealthcare/Chexpert/blob/7e621796b7d751024843ec3af23595dfbf4e6817/data/imgaug.py#L13). Did you try things like RandomCrop?

Also, how do you determine the pixel_mean and pixel_std? Does the image transformation matter a lot on the final performance? I found many people use the following normalization for the original RGB images.
```
transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
```
Meanwhile, you convert the images into Gray. I guess that's the reason why you choose not to use such normalization. Is my understanding correct?

Any suggestion would be appreciated :-) Thanks.

**Comment by yil8** [comment]
@deadpoppy your turn...

**Comment by deadpoppy** [comment]
of cause !you are right!you can statistic the gray images and compute the pixel_mean and pixel_std.it must be 128 and 64.
about another question, I have to say that I haven't tried 'RandomCrop'. And I believe  A complete picture is important for determining disease.

**Comment by deadpoppy** [comment]
@nijianmo
