### ISSUE TITLE
heatmaps wth avg_max pooling

### ISSUE THREAD

**Issue by aakash-saboo** [jfhealthcare/Chexpert#15]
Hi. can you tell me , how to get heatmaps when pooling is avg_max?
is it correct to take the last convolution layer of the backbone and use its gradient and activations to generate heatmap?

**Comment by aakash-saboo** [comment]
Hi
I have been trying to make heatmaps with avg_max pooling.

I do full forward propagation. Then i do backward propagation from one branch for a specific class(as there are 5 branches each corresponding to different class) and I save the gradients and activations from the last conv layer of the backbone(in case of densenet121, its model.backbone.features.denseblock4.denselayer16.conv2). I use these saved gradients and activations to compute gradcam.
Is this the right approach?

**Comment by deadpoppy** [comment]
Our code does not yet support the heatmap of AVG_AMX pooling. In principle, I think you're doing the right thing, and I'm curious about what you're getting. @aakash-saboo

**Comment by yww211** [comment]
Hi，
We have implemented supported three types of heatmaps, you can check in this [Pull Request](https://github.com/jfhealthcare/Chexpert/tree/PROB_POOL). @aakash-saboo
