### ISSUE TITLE
training the model on all 14 parameters give lower AUC score

### ISSUE THREAD

**Issue by amanrs** [jfhealthcare/Chexpert#18]
Thanks for open-sourcing your code it's a huge help. I trained your model on image size of 128X128 images and got the AUC scores as follows:
Cardiomegaly : 0.8282
Edema: 0.8878
Consolidation: 0.9250
Atelectasis: 0.8216
Pleural_Effusion: 0.9227

but when I trained the model with all 14 classes, the AUC scores of the following reduced to :
Cardiomegaly : 0.7698
Edema: 0.7843
Consolidation: 0.8443
Atelectasis: 0.7332
Pleural_Effusion: 0.7595

is there a way to keep the AUC scores high while training on

**Comment by deadpoppy** [comment]
If you use the training data of 14 kinds of disease, I think the first thing you face is data imbalance problem. There is little data on some of the 14 diseases. @amanrs

**Comment by amanrs** [comment]
yes, that is what I am facing I tried doing upsampling and training it on a smaller dataset but it didn't make any difference in the AUC scores there was a slight increase and  a slight decrease in the class results

**Comment by anjany** [comment]
Hi @amanrs : For the model you trained with all 14 classes, do you happen to have the AUC scores of the other classes too? I mean, for the ones other than the five you have reported here?
