### ISSUE TITLE
Questions about normalization and auc score 

### ISSUE THREAD

**Issue by jeonghwaYoo** [jfhealthcare/Chexpert#21]
Hello. I really appreciate for your sharing this great project!
I have some questions. 

You set the `pixel_mean` and `pixel_std` like this. 
https://github.com/jfhealthcare/Chexpert/blob/96d4906a54dc22a78c57fd2cd7edcdd3165db36d/config/example_PCAM.json#L9-L10

I have seen a lot of examples of obtaining mean and std from data and normalizing it in the following way.
https://github.com/jfhealthcare/Chexpert/blob/96d4906a54dc22a78c57fd2cd7edcdd3165db36d/data/utils.py#L44-L68
Is there any problem even if I fix it to a specific value rather than mean and std obtained from the data?
If so, on what basis was the value set? I'm trying to test it on a 16 bit image.

And I have another question about the auc score.
Auc score of your model on the chexpert leaderboard is 0.929.
When I tested the model you provided with validation data, I got an auc score of 0.89.
I think you used the ensemble method. Should I implement additional code 
to achieve similar performance to yours?

Thank you!

**Comment by yil8** [comment]
@deadpoppy can you take a look?

**Comment by deadpoppy** [comment]
Hi @jeonghwaYoo 
definitely! a specific value rather than mean and std obtained from the data will affect your model. but my `pixel_mean`and `pixel_std` are statistics from the data.
about the AUC score, we just provide a single model here. You may have to implement the ensemble method by yourself.

**Comment by jeonghwaYoo** [comment]
@yil8 @deadpoppy  
Really thank you for your response! 
and I have another question about labeling. 
You have treat the uncertain data as follows:
when the data is about cardiomegaly, consolidation, pleural effusion -> positive (1)
edema, atelectasis -> negative (0) 
What is the basis for this setting?

**Comment by yww211** [comment]
> Hi @jeonghwaYoo @jeonghwaYoo 
> definitely! a specific value rather than mean and std obtained from the data will affect your model. but my `pixel_mean`and `pixel_std` are statistics from the data.
> about the AUC score, we just provide a single model here. You may have to implement the ensemble method by yourself.

I guess the `pixel_mean` and the `pixel_std` are not statistics from the data. Instead, they are  actually the empirical values.
Even if the `pixel_mean`and `pixel_std`  of real data are not what we set in the config json, from our observation and experiments, the value setting in our config json is very colse  to the values calculated from a certain image dataset.

Am i right? @yil8

**Comment by yil8** [comment]
@yww211 I remember setting the `pixel_mean` and `pixel_std` to either 128/64 or training statistics has almost zero effects on the performance

**Comment by jeongHwarr** [comment]
@yww211  @yil8  Okay I got it. Thank you !
