### ISSUE TITLE
Use pre-trained model on customised dataset

### ISSUE THREAD

**Issue by ScorpLee** [jfhealthcare/Chexpert#22]
Hi,

Thanks for sharing this. I'm wondering if I can use the pre-trained model on a customised dataset and what type of result do I expect to get? I have some chest CT scan but not labelled and I'm not a medic expert nor a medical student (aka radiograph mean nothing to me) and I'm wondering if I feed those data in, would it give me detections of the possibilities of 14 observations? Maybe I need to adjust the model?

**Comment by yil8** [comment]
@ScorpLee I don't think your proposal works. Chest CT is 3D data while chest X-ray is 2D. Although you could use the coronal view of CT to obtain the 2D data, the underly image characteristics may be quite different.
