### ISSUE TITLE
use equalizeHist enhance the images before feed images into network?

### ISSUE THREAD

**Issue by lordbutters** [jfhealthcare/Chexpert#24]
I noticed that in  `config/example.json` , there is a parameter says that `"use_equalizeHist": true`, so you have used equalizeHist to 
 enhance the images before feed them into you network?

**Comment by deadpoppy** [comment]
yes @lordbutters

**Comment by lordbutters** [comment]
> yes @lordbutters

But there is only a small difference between original images and equalizaHist images, why do you use this treatment? Is there a big improvement compared to the original images on AUC?

**Comment by deadpoppy** [comment]
Yes, normal scenes are mostly reasonable images, but in our real scenes, there are always cases where the image is too bright or too dark. So this is a common method. @lordbutters
