### ISSUE TITLE
Can you add a license file?

### ISSUE THREAD

**Issue by pluskid** [jfhealthcare/Chexpert#26]
Great work! Thanks for open sourcing the code! Can you add a LICENSE file ([github doc](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository))? Having an explicit open source license makes it much easier for us (and others) to built on top of your code. Otherwise the code is copyright protected by default. Thanks a lot!

**Comment by yil8** [comment]
@pluskid thanks for your suggestion, which license would you recommend? We basically don't need to place any restrictions on this piece of code. I'm guessing Apache license 2.0?

**Comment by pluskid** [comment]
Thanks for the prompt reply! I’m not an expert either. Apache and BSD seem to be both common in the field.

**Comment by yil8** [comment]
@pluskid Apache license 2.0 added
