### ISSUE TITLE
请问提供的预训练模型是AVG_MAX的吗？

### ISSUE THREAD

**Issue by Danie1Hayes** [jfhealthcare/Chexpert#27]
感谢大神的作品，能否提供可以生成heatmap的预训练模型，比如PCAM，LSE等的模型！感谢

**Comment by yil8** [comment]
@deadpoppy @yww211 我们有PCAM, LSE的模型吗？

**Comment by deadpoppy** [comment]
请简单训练一下即可生成heatmap，我们仅提供比赛使用的MAX_AVG权重，该权重在代码库中可以找到。  @Danie1Hayes
