### ISSUE TITLE
Model added to the torchxrayvision library

### ISSUE THREAD

**Issue by ieee8023** [jfhealthcare/Chexpert#29]
Hello! I added this model to the torchxrayvision library! Let me know if there is anything you would liked changed.

Here is our documentation:
https://github.com/mlmed/torchxrayvision#models-demo-notebook

I added the citation here: https://github.com/mlmed/torchxrayvision/tree/master/torchxrayvision/baseline_models/jfhealthcare

**Comment by yil8** [comment]
@ieee8023 Sure, thanks for your interest and effort in doing so!
