### ISSUE TITLE
About “label_header” from dataset.py

### ISSUE THREAD

**Issue by BUAAtao** [jfhealthcare/Chexpert#3]
self._label_header = [
                header[3],
                header[6],
                header[7],
                header[9],
                header[11]]
对应train.csv上列号是不是有问题，改成
self._label_header = [
                header[7],
                header[10],
                header[11],
                header[13],
                header[15]]?

**Comment by deadpoppy** [comment]
Good discovery! solved now. Sorry, I ignored it before,  it's not going to affect your results, it might affect the labels that you show. @BUAAtao
