### ISSUE TITLE
Example Configuration

### ISSUE THREAD

**Issue by liberbey** [jfhealthcare/Chexpert#30]
Hi! We tried the pretrained model with given example.json configuration file, but we could not get your results given in the readme file. Could you share your configuration file so we can get the same results? Thanks!

Here are the results we get:

```
Cardiomegaly auc 0.7554274084124831
Edema auc 0.8814044605183846
Consolidation auc 0.8677455357142857
Atelectasis auc 0.84928
Pleural Effusion auc 0.9034926470588235
```

**Comment by yil8** [comment]
@yww211 @deadpoppy can you guys take a look?

**Comment by yww211** [comment]
Maybe we need reproduce the results again？ @deadpoppy

**Comment by deadpoppy** [comment]
hi , @liberbey  we already shared our configuration , and some people have got the same result too .refer to #6

**Comment by deadpoppy** [comment]
and you can reproduce it. @yww211

**Comment by liberbey** [comment]
Thanks for your answers. So, I have few questions.

- As far as I understood, example.json is not the exact same configuration that you get the results in readme, am I right?
- Did you use  "save_index" as [0,1,2,3,4] or ["0","3"]?
- Did you use "pixel_mean": 128.0 and "pixel_std": 64.0 as it is or calculated them?
- Do you have a published article on this?
- And finally, do you have any advices about these configurations?

**Thank you very much!**

**Comment by liberbey** [comment]
> Maybe we need reproduce the results again？ @deadpoppy

That would be very helpful btw. @yww211

**Comment by deadpoppy** [comment]
Hi, @liberbey thanks for your question. Specifically, I use the code base, use different oversampling and model preservation strategies on the example configurations you see, and then get different performance models and integrate them. The model provided in the codebase is the best single model in my ensemble model. It is recommended to pay more attention to a single disease in multitasking. The above is also my suggestion. Good luck

**Comment by deadpoppy** [comment]
about the "pixel_mean": 128.0 and "pixel_std": 64.0, you can refer to #21  @liberbey

**Comment by liberbey** [comment]
Thanks for your answers. @deadpoppy
