### ISSUE TITLE
Tensorflow trained model

### ISSUE THREAD

**Issue by bhatuzdaname** [jfhealthcare/Chexpert#31]
Hi,

Do you also have a pre trained model that is compatible with tensorflow? I have been converting the pytorch model here into onnx and then that into tensorflow and am getting a lot of extra nodes as part of the conversion. It would be great if you could provide a tensorflow version

**Comment by yil8** [comment]
@bhatuzdaname No, I don't think so and sorry about that

**Comment by Yandychang1** [comment]
Wondering what network is the backbone of the best network provided.

**Comment by bhatuzdaname** [comment]
@yil8 no problem, thank you!

**Comment by yww211** [comment]
> Wondering what network is the backbone of the best network provided.

@Yandychang1
DenseNet121 has the highest mAUC for single model, but different backbones have slightly difference on mAUC and the recomended way is to try different backbones as much as possible before you ensembling them together.
