### ISSUE TITLE
Output probabilities of all 14 classes 

### ISSUE THREAD

**Issue by abhirooptalasila** [jfhealthcare/Chexpert#36]
How can we predict the output probabilities of all 14 classes?
In the `example.json` file, I see _num_classes_ has 5 elements. How do I extend it?

**Comment by Shirugo** [comment]
Hello, I also want to know how to expand the output to 14 categories, please do you solve this problem? If you solve it, would you please let me know how to modify the code?

**Comment by abhirooptalasila** [comment]
The test set provided in the dataset apparently only has ground truth for those 5 classes. Nothing we can do :/
