### ISSUE TITLE
Is it trained via downsampled resolution?

### ISSUE THREAD

**Issue by ZhenyF** [jfhealthcare/Chexpert#8]
Hi,
Thanks for the work!

I would like to know which dataset do you use for training？The original one (~439G) or the downsampled one (~11G)

**Comment by yil8** [comment]
@ZhenyF I remember we rescaled the original images to 1024x1024

**Comment by ZhenyF** [comment]
Many thanks for the reply, and may I know the accuracy on the validation set? Limited by the space, I can only try your model on the downsampled set, so I would like to use it as a contrast.

**Comment by deadpoppy** [comment]
> Many thanks for the reply, and may I know the accuracy on the validation set? Limited by the space, I can only try your model on the downsampled set, so I would like to use it as a contrast.

**Comment by deadpoppy** [comment]
> Many thanks for the reply, and may I know the accuracy on the validation set? Limited by the space, I can only try your model on the downsampled set, so I would like to use it as a contrast.
