### ISSUE TITLE
enhance_times=1 or 2 for the given pretrained model?

### ISSUE THREAD

**Issue by aakash-saboo** [jfhealthcare/Chexpert#9]
Hi.
Thanks for your work.
Can you please tell me that the pretrained model which is given is trained using enhance_time=1 or enhance_time=2?

thanks

**Comment by deadpoppy** [comment]
> Can you please tell me that the pretrained model which is given is trained using enhance_time=1 or enhance_time=2?

'1' as shown in the 'config/example.json'
